Noticed that the set-up for 2d_diffusion was not the actuall paper generating function. 
trying 
!conda activate ai_scientist
!python launch_scientist.py --model "deepseek-coder-v2-0724" --experiment nanoGPT_lite --num-ideas 2

Error:
/bin/bash: line 1: conda: command not found
Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 1, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'


pip install openai
!conda activate ai_scientist
!python launch_scientist.py --model "deepseek-coder-v2-0724" --experiment nanoGPT_lite --num-ideas 2

Error:
/bin/bash: line 1: conda: command not found
Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 11, in <module>
    from aider.coders import Coder
ModuleNotFoundError: No module named 'aider'


Investigating what conda activate ai_scientist does...
It actives isolated environments. Since Google colab is already an isolated environment ,I will skip this command.
Also, I noticed it was trying to launch the nanoGTP_lite experiment. I changed it to 2d_diffusion
!python launch_scientist.py --model "deepseek-coder-v2-0724" --experiment nanoGPT_lite --num-ideas 2

Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 11, in <module>
    from aider.coders import Coder
ModuleNotFoundError: No module named 'aider'


!pip install aider
Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 11, in <module>
    from aider.coders import Coder
ModuleNotFoundError: No module named 'aider.coders'


!pip install aider
from aider.coders import Coder
ModuleNotFoundError: No module named 'aider.coders'


Peculiar!!! Has the library depreciated? I'll investigate...
The website
https://aider.chat/docs/troubleshooting/aider-not-found.html
recommended this solution:
!python -m pip install aider-chat
!python -m aider
Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 18, in <module>
    from ai_scientist.perform_review import perform_review, load_paper, perform_improvement
  File "/content/AI-Scientist/ai_scientist/perform_review.py", line 4, in <module>
    from pypdf import PdfReader
ModuleNotFoundError: No module named 'pypdf'

?
!pip install pypdf
ModuleNotFoundError: No module named 'pypdf'

???
!pip install pymupdf
ModuleNotFoundError: No module named 'pymupdf4llm'

>.< ????
!pip install pymupdf4llm
Using GPUs: [0]
Using OpenAI API with deepseek-coder-v2-0724.
Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 352, in <module>
    api_key=os.environ["DEEPSEEK_API_KEY"], base_url="https://api.deepseek.com"
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'DEEPSEEK_API_KEY'


Strangly it cannot access the envitonmental vairables in google colab. 
import os
from google.colab import userdata
DEEPSEEK_API_KEY = userdata.get('DEEPSEEK_API_KEY')
api_key = os.environ["DEEPSEEK_API_KEY"] = "sk-#####################"
It started generating ideas...

Changed above code to import os
from google.colab import userdata
DEEPSEEK_API_KEY = userdata.get('DEEPSEEK_API_KEY')
api_key = os.environ["DEEPSEEK_API_KEY"] = DEEPSEEK_API_KEY

